MODEL:

TRAIN:
  train_data_dir: [
    '../dataset/lmdb/str/TextZoom/train1',
    '../dataset/lmdb/str/TextZoom/train2',
  ] 
  batch_size: 8
  width: 128
  height: 32
  epochs: 500
  cuda: false
  ngpu: 0
  workers: 0
  resume: ''
  ckpt_dir: './ckpt/'
  voc_type: 'all' 
  saveInterval: 200
  displayInterval: 100 
  adadelta: False
  lr: 0.001
  adam: True
  beta1: 0.5
  manualSeed: 1234
  max_len: 100
  keep_ratio: False
  down_sample_scale: 2

  VAL:
    val_data_dir: [
      '../dataset/lmdb/str/TextZoom/test/hard',
      '../dataset/lmdb/str/TextZoom/test/easy',
      '../dataset/lmdb/str/TextZoom/test/medium',
    ]
    n_vis: 10
    vis_dir: 'demo'
    valInterval: 200 #-1, val at the end of epoch
    aster_pretrained: './pretrained_rec_weights/Aster.pth.tar'
    moran_pretrained: './pretrained_rec_weights/Moran.pth'
    crnn_pretrained: './pretrained_rec_weights/crnn.pth'

TEST:
  checkpoint: ''
  test_data_dir: [
  ]

CONVERT:
  image_dir:
  lmdb_dir:
  n_convert: 10
